-- 코드를 작성해주세요
SELECT F1.ID, F2.FISH_NAME, F1.LENGTH
FROM FISH_INFO AS F1
JOIN FISH_NAME_INFO AS F2
ON F1.FISH_TYPE = F2.FISH_TYPE
WHERE F1.FISH_TYPE IN (SELECT FISH_TYPE FROM FISH_INFO 
                       GROUP BY FISH_TYPE 
                       HAVING LENGTH =MAX(LENGTH))
ORDER BY ID