-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN HR_GRADE G ON E.EMP_NO=G.EMP_NO
GROUP BY G.YEAR, G.EMP_NO
HAVING G.YEAR='2022'
ORDER BY SCORE DESC
LIMIT 1